### ISSUE TITLE
Failed to download package '36.2.1.0'

### ISSUE THREAD

**Issue by kfrancis** [tallesl/net-36#1]
Started to get build errors on Azure DevOps:

```
##[error]The nuget command failed with exit code(1) and error(Failed to download package '36.2.1.0' from 'https://www.nuget.org/api/v2/package/36/2.1.0'.
```

Not sure what happened, though I think it's because the name of the package is a number itself.

**Comment by tallesl** [comment]
Maybe it's some intermittent network error?

I just tested installing the library in a blank console project and got no problems. Also, the URL in the error message works fine: https://www.nuget.org/api/v2/package/36/2.1.0
